const data = {
  products: [
    {
      id: 1,
      name: "Green Shirt",
      title: "green-shirt",
      category: "Shirts",
      image: "/images/shirt.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      countInStock: 20,
      description: "A green shirt",
    },
    {
      id: 2,
      name: "Cap",
      title: "sport-cap",
      category: "Accesories",
      image: "/images/cap.jpg",
      price: 80,
      brand: "Canyon",
      rating: 4.2,
      countInStock: 20,
      description: "A sport cap",
    },
    {
      id: 3,
      name: "Slim Pant",
      title: "slim-patn",
      category: "Pants",
      image: "/images/pant.jpg",
      price: 90,
      brand: "Diesel",
      rating: 4.5,
      countInStock: 20,
      description: "A slim pant",
    },
    {
      id: 4,
      name: "Vans Shoes",
      title: "vans-shoes",
      category: "Shoes",
      image: "/images/shoe.jpg",
      price: 90,
      brand: "Vanns",
      rating: 4.5,
      countInStock: 20,
      description: "Black vanns shoes",
    },
    {
      id: 5,
      name: "Slipper",
      title: "slipper",
      category: "Accesories",
      image: "/images/slipper.jpg",
      price: 95,
      brand: "Zara",
      rating: 4.5,
      countInStock: 20,
      description: "Soft black slipper",
    },
    {
      id: 6,
      name: "luxury handbag",
      title: "luxury-handbag",
      category: "Accesories",
      image: "/images/handbag.jpg",
      price: 75,
      brand: "Gucci",
      rating: 4.5,
      countInStock: 20,
      description: "Luxury handbag",
    },
  ],
};

export default data;
